### ISSUE TITLE
Log date formatter changed with the latest build

### ISSUE THREAD

**Issue by frebib** [lucko/gChat#13]
Thanks for updating/fixing the logging in the latest build.
The format changed for me, though
```
2019-11-25T20:45Z [INFO] [survival] <frebib> (quact)
2019-12-08T15:17Z [INFO] [survival] <frebib> zzzzzzz
22:27:04 [INFO] [creative] <frebib> test
22:27:04 [INFO] [creative] <frebib> hi
22:27:05 [INFO] [creative] <frebib> sup
```

Our Bungeecord instances uses a different date format specified at runtime:
https://github.com/spritsail/bungeecord/commit/b79e9f89ad5d6559180c12e17216fc98cbb8eb4d
The ConciseFormatter that was used before reads that variable, and defaults to `HH:mm:ss`:
https://github.com/SpigotMC/BungeeCord/blob/master/log/src/main/java/net/md_5/bungee/log/ConciseFormatter.java#L17

Could this override be re-added, please

**Comment by frebib** [comment]
Better still, it looks like the `ConciseFormatter` can still be used, but using one of the Lombok constructors, as upstream does here: https://github.com/SpigotMC/BungeeCord/commit/bf673c5d8b965a035ab55753cfbc6038f8a4cfbb#diff-bb12962309e5cb9baadb0b934fd0f074R29

The empty constructor is Protected, which is why it throws nasty warnings
```
2020-02-25T12:06Z [WARNING] Exception encountered when loading plugin: gChat
java.lang.IllegalAccessError: tried to access method java.util.logging.Formatter.<init>()V from class me.lucko.gchat.GChatPlugin
    at me.lucko.gchat.GChatPlugin.loadLogger(GChatPlugin.java:208)
    at me.lucko.gchat.GChatPlugin.loadConfig(GChatPlugin.java:183)
    at me.lucko.gchat.GChatPlugin.onEnable(GChatPlugin.java:87)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
https://docs.oracle.com/javase/8/docs/api/java/util/logging/Formatter.html#Formatter--

**Comment by lucko** [comment]
Will accept a PR for this
