### ISSUE TITLE
Error on enable on latest waterfall version

### ISSUE THREAD

**Issue by lusu007** [lucko/gChat#16]
Im getting an error when using gChat on the latest Waterfall version.

```bash
[21:22:38] [main/WARN]: Error enabling plugin gChat
java.lang.NoClassDefFoundError: net/md_5/bungee/log/ConciseFormatter
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3215) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3420) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2631) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:382) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.log.ConciseFormatter
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[proxy.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 9 more```

**Comment by mdcfe** [comment]
This seems like a duplicate of #11 - what build of gChat are you running?

**Comment by lusu007** [comment]
Oh sorry, I didnt saw the existing issue.
I'm using the newest one (build 10).

**Comment by magrigry** [comment]
Hey, it looks like same error is occuring with build #11 and waterfall 384.

```
java.lang.NoClassDefFoundError: net/md_5/bungee/log/ConciseFormatter
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_275]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_275]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_275]
        at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_275]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:382) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.log.ConciseFormatter
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[waterfall-1.16-384.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 9 more```

**Comment by strich3** [comment]
pls fix it :)

**Comment by KnightBlood** [comment]
pls fix it :)

**Comment by Nooxico** [comment]
Well i guess i'm just posting this hoping he'll see the issue and that he'll fix it
